config:
    resource: "@ConfigBundle/Controller/"
    type:     annotation
    prefix:   /config

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

usuario:
    resource: "@UsuarioBundle/Controller/"
    type:     annotation
    prefix:   /usuario

profesor:
    resource: "@ProfesorBundle/Controller/"
    type:     annotation
    prefix:   /profesor

index:
    resource: "@IndexBundle/Controller/"
    type:     annotation
    prefix:   /

alumno:
    resource: "@AlumnoBundle/Controller/"
    type:     annotation
    prefix:   /alumno

empresa:
    resource: "@EmpresaBundle/Controller/"
    type:     annotation
    prefix:   /empresa

logout:
    path: /usuario/usuarios/logout
