# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        UsuarioBundle\Entity\Usuario: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory: ~
        my_db_provider:
            entity:
                class: UsuarioBundle:Usuario
                property: username


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern: ^/admin
            http_basic: ~

        usuarios:
            pattern: ^/ #tendra acceso desde la home#
            anonymous: ~
            provider: my_db_provider
            form_login:
                login_path: /usuario/usuarios/login
                check_path: /usuario/usuarios/login
            logout:
                path:   /usuario/usuarios/logout
                target: /usuario/usuarios


        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
